# Dart Code Analysis Options
# 用于配置 Dart 代码分析规则
# P2: Enhanced linting rules for stricter type safety and code quality

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ==================== Error Rules (Critical) ====================
    avoid_empty_else: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # ==================== Type Safety (Strict) ====================
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    prefer_void_to_null: true
    strict_raw_type: true
    # Uncomment below for even stricter type checking:
    # avoid_annotating_with_dynamic: true

    # ==================== Null Safety ====================
    avoid_null_checks_in_equality_operators: true
    use_if_null_to_convert_nulls_to_bools: true

    # ==================== Async Best Practices ====================
    avoid_void_async: true
    unawaited_futures: true
    discarded_futures: true

    # ==================== Style Rules ====================
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    combinators_ordering: true
    directives_ordering: true
    eol_at_end_of_file: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_asserts_in_initializer_lists: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_to_list_in_spreads: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true

    # ==================== Documentation (Optional - Uncomment to enable) ====================
    # public_member_api_docs: true
    # package_api_docs: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"
    - "lib/generated/**"

  errors:
    invalid_annotation_target: ignore
    # Treat important issues as errors
    missing_return: error
    missing_required_param: error
    dead_code: warning
    deprecated_member_use: warning
    unused_import: warning
    unused_local_variable: warning

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
