from uuid import UUID
from datetime import datetime
import grpc
from loguru import logger

# Import the service implementation base
# Note: These files are generated by protoc
try:
    from app.gen.galaxy.v1 import galaxy_service_pb2, galaxy_service_pb2_grpc
except ImportError:
    # Fallback for development if protos are not generated yet
    logger.warning("Galaxy gRPC proto files not found. Run 'make proto-gen-legacy'.")
    galaxy_service_pb2 = None
    galaxy_service_pb2_grpc = None

from app.services.galaxy_service import GalaxyService
from app.db.session import AsyncSessionLocal

class GalaxyGrpcServiceImpl:
    def __init__(self, db_session_factory):
        self.db_session_factory = db_session_factory

    async def UpdateNodeMastery(self, request, context):
        """
        gRPC implementation of UpdateNodeMastery.
        """
        async with self.db_session_factory() as db:
            galaxy_service = GalaxyService(db)
            
            try:
                # Convert proto Timestamp to Python datetime
                version = None
                if request.version:
                    version = datetime.fromtimestamp(request.version.seconds + request.version.nanos / 1e9)
                
                result = await galaxy_service.update_node_mastery(
                    user_id=UUID(request.user_id),
                    node_id=UUID(request.node_id),
                    new_mastery=request.mastery,
                    reason=request.reason,
                    version=version,
                    request_id=request.request_id,
                    revision=request.revision
                )
                
                if not result.get("success"):
                    # For gRPC, we can return status code but also the current revision for the client to sync
                    # Use custom response fields
                    return galaxy_service_pb2.UpdateNodeMasteryResponse(
                        success=False,
                        reason=result.get("reason", "conflict"),
                        request_id=request.request_id,
                        current_revision=result.get("current_revision", 0)
                    )

                return galaxy_service_pb2.UpdateNodeMasteryResponse(
                    success=True,
                    old_mastery=int(result.get("old_mastery", 0)),
                    new_mastery=int(result.get("new_mastery", 0)),
                    request_id=request.request_id,
                    current_revision=result.get("current_revision", 0)
                )
                
            except Exception as e:
                logger.error(f"gRPC UpdateNodeMastery failed: {e}")
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(str(e))
                return galaxy_service_pb2.UpdateNodeMasteryResponse(success=False, reason=str(e))
