"""add_galaxy_v2_tables

Revision ID: 54e1f05154ad
Revises: b3849bc7b0cd
Create Date: 2025-12-16 17:32:27.621493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '54e1f05154ad'
down_revision: Union[str, None] = 'b3849bc7b0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    op.create_table('node_relations',
    sa.Column('source_node_id', app.models.base.GUID(), nullable=False),
    sa.Column('target_node_id', app.models.base.GUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_relations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_relations_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_relations_target_node_id'), ['target_node_id'], unique=False)

    op.create_table('node_expansion_queue',
    sa.Column('trigger_node_id', app.models.base.GUID(), nullable=False),
    sa.Column('trigger_task_id', app.models.base.GUID(), nullable=True),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('expansion_context', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expanded_nodes', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trigger_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['trigger_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_expansion_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_expansion_queue_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_expansion_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_expansion_queue_user_id'), ['user_id'], unique=False)

    op.create_table('study_records',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('node_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.Column('mastery_delta', sa.Float(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_records_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_records_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_seed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_task_id', app.models.base.GUID(), nullable=True))
        
        if is_sqlite:
            batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=True))
        else:
            op.execute('CREATE EXTENSION IF NOT EXISTS vector')
            batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
            
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glow_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('position_angle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('icon_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_node_id', app.models.base.GUID(), nullable=True))
        batch_op.add_column(sa.Column('auto_expand_enabled', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_knowledge_node_id', 'knowledge_nodes', ['knowledge_node_id'], ['id'])

    with op.batch_alter_table('user_node_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_study_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('study_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_collapsed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_study_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('decay_paused', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('next_review_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_unlock_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('mastery_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_node_status_next_review_at'), ['next_review_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_node_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_node_status_next_review_at'))
        batch_op.alter_column('mastery_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('first_unlock_at')
        batch_op.drop_column('next_review_at')
        batch_op.drop_column('decay_paused')
        batch_op.drop_column('last_study_at')
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('is_collapsed')
        batch_op.drop_column('study_count')
        batch_op.drop_column('total_study_minutes')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('auto_expand_enabled')
        batch_op.drop_column('knowledge_node_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('icon_name')
        batch_op.drop_column('position_angle')
        batch_op.drop_column('glow_color')

    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('embedding')
        batch_op.drop_column('source_task_id')
        batch_op.drop_column('source_type')
        batch_op.drop_column('is_seed')
        batch_op.drop_column('keywords')
        batch_op.drop_column('name_en')

    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_records_node_id'))
        batch_op.drop_index(batch_op.f('ix_study_records_deleted_at'))

    op.drop_table('study_records')
    with op.batch_alter_table('node_expansion_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_expansion_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_node_expansion_queue_status'))
        batch_op.drop_index(batch_op.f('ix_node_expansion_queue_deleted_at'))

    op.drop_table('node_expansion_queue')
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_relations_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_node_relations_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_node_relations_deleted_at'))

    op.drop_table('node_relations')
    # ### end Alembic commands ###