"""add_notifications_and_user_preferences

Revision ID: 6a9c3cc94147
Revises: a1b2c3d4e5f6
Create Date: 2025-12-16 14:51:53.759684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import GUID # Import GUID

# revision identifiers, used by Alembic.
revision: str = '6a9c3cc94147'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', GUID(), nullable=False), # Changed to GUID()
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('parse_degraded', sa.Boolean(), nullable=True))
        batch_op.drop_index('idx_chat_deleted_at') # Note: when using batch_op, often don't need table_name
        batch_op.create_index(batch_op.f('ix_chat_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_unique_constraint("uq_chat_messages_message_id", ['message_id'])

    # op.add_column('error_records', sa.Column('subject_id', sa.Integer(), nullable=True))
    # op.drop_index(op.f('idx_error_deleted_at'), table_name='error_records')
    # op.create_index(op.f('ix_error_records_deleted_at'), 'error_records', ['deleted_at'], unique=False)
    # op.create_foreign_key(None, 'error_records', 'subjects', ['subject_id'], ['id'])
    # op.create_index('idx_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    # op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    # op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    # op.drop_index(op.f('idx_jobs_deleted_at'), table_name='jobs')
    # op.create_index(op.f('ix_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    # op.drop_index(op.f('idx_plans_deleted_at'), table_name='plans')
    # op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    # op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # op.alter_column('subjects', 'created_at',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.DateTime(),
    #            nullable=False)
    # op.create_index(op.f('ix_subjects_category'), 'subjects', ['category'], unique=False)
    # op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    # op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    # op.drop_index(op.f('idx_tasks_deleted_at'), table_name='tasks')
    # op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.add_column('users', sa.Column('schedule_preferences', sa.JSON(), nullable=True))
    # op.drop_index(op.f('idx_users_deleted_at'), table_name='users')
    # op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.create_index(op.f('idx_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.drop_column('users', 'schedule_preferences')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.create_index(op.f('idx_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_category'), table_name='subjects')
    op.alter_column('subjects', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subjects', 'updated_at')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.create_index(op.f('idx_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_jobs_deleted_at'), table_name='jobs')
    op.create_index(op.f('idx_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_keys')
    op.drop_constraint(None, 'error_records', type_='foreignkey')
    op.drop_index(op.f('ix_error_records_deleted_at'), table_name='error_records')
    op.create_index(op.f('idx_error_deleted_at'), 'error_records', ['deleted_at'], unique=False)
    op.drop_column('error_records', 'subject_id')
    op.drop_constraint(None, 'chat_messages', type_='unique')
    op.drop_index(op.f('ix_chat_messages_deleted_at'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_deleted_at'), 'chat_messages', ['deleted_at'], unique=False)
    op.drop_column('chat_messages', 'parse_degraded')
    op.drop_column('chat_messages', 'message_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
