"""add_social_auth_fields

Revision ID: ad7a53964495
Revises: d1e2f3a4b5c6
Create Date: 2025-12-23 20:36:35.648370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import app
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'ad7a53964495'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_histories',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_histories_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_histories_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_histories_user_id'), ['user_id'], unique=False)

    op.create_table('push_preferences',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('active_slots', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('enable_curiosity', sa.Boolean(), nullable=False),
    sa.Column('persona_type', sa.String(length=50), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('last_push_time', sa.DateTime(), nullable=True),
    sa.Column('consecutive_ignores', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_preferences_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_preferences_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_error_records_subjects', 'subjects', ['subject_id'], ['id'])

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.create_index(batch_op.f('ix_friendships_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='grouprole'),
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('TEXT', 'TASK_SHARE', 'PROGRESS', 'ACHIEVEMENT', 'CHECKIN', 'SYSTEM', name='messagetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))
        batch_op.create_index(batch_op.f('ix_group_messages_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('group_task_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_task_claims_group_task_id'), ['group_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_task_claims_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('group_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_tasks_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SQUAD', 'SPRINT', name='grouptype'),
               existing_nullable=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_idempotency_user_id'))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_jobs_type'))
        batch_op.create_index('idx_jobs_status_timeout', ['status', 'timeout_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sqlite.JSON(),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_subjects_category'))
        batch_op.drop_index(batch_op.f('idx_subjects_is_active'))
        batch_op.drop_index(batch_op.f('idx_subjects_name'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_preferences', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('apple_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wechat_unionid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('registration_source', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_apple_id'), ['apple_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_unionid'), ['wechat_unionid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wechat_unionid'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_apple_id'))
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('registration_source')
        batch_op.drop_column('wechat_unionid')
        batch_op.drop_column('apple_id')
        batch_op.drop_column('google_id')
        batch_op.drop_column('weather_preferences')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subjects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_subjects_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_subjects_category'), ['category'], unique=False)

    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sqlite.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index('idx_jobs_status_timeout', postgresql_where=sa.text("status = 'running'"))
        batch_op.create_index(batch_op.f('idx_jobs_type'), ['type'], unique=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_idempotency_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('SQUAD', 'SPRINT', name='grouptype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('group_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_tasks_group_id'))

    with op.batch_alter_table('group_task_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_task_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_task_claims_group_task_id'))

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_group_id'))
        batch_op.alter_column('message_type',
               existing_type=sa.Enum('TEXT', 'TASK_SHARE', 'PROGRESS', 'ACHIEVEMENT', 'CHECKIN', 'SYSTEM', name='messagetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='grouprole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_friend_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)

    with op.batch_alter_table('push_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_preferences_deleted_at'))

    op.drop_table('push_preferences')
    with op.batch_alter_table('push_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_histories_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_histories_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_push_histories_content_hash'))

    op.drop_table('push_histories')
    # ### end Alembic commands ###
