"""initial_migration_with_all_models

Revision ID: fb11f8afb34c
Revises: 
Create Date: 2025-12-27 01:11:44.399720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'fb11f8afb34c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create pgvector extension if not already present
    # This is required for vector embedding support
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('pos', sa.String(length=50), nullable=True),
    sa.Column('definitions', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dictionary_entries', schema=None) as batch_op:
        batch_op.create_index('idx_dict_word', ['word'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionary_entries_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionary_entries_word'), ['word'], unique=True)

    op.create_table('groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.Enum('SQUAD', 'SPRINT', 'OFFICIAL', name='grouptype'), nullable=False),
    sa.Column('focus_tags', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('sprint_goal', sa.Text(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('join_requires_approval', sa.Boolean(), nullable=False),
    sa.Column('total_flame_power', sa.Integer(), nullable=False),
    sa.Column('today_checkin_count', sa.Integer(), nullable=False),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('idx_group_public', ['is_public'], unique=False)
        batch_op.create_index('idx_group_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sector_code', sa.String(length=20), server_default='VOID', nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=True),
    sa.Column('glow_color', sa.String(length=7), nullable=True),
    sa.Column('position_angle', sa.Float(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='avatarstatus'), nullable=False),
    sa.Column('pending_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('flame_level', sa.Integer(), nullable=False),
    sa.Column('flame_brightness', sa.Float(), nullable=False),
    sa.Column('depth_preference', sa.Float(), nullable=False),
    sa.Column('curiosity_preference', sa.Float(), nullable=False),
    sa.Column('schedule_preferences', sa.JSON(), nullable=True),
    sa.Column('weather_preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'INVISIBLE', name='userstatus'), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('apple_id', sa.String(length=255), nullable=True),
    sa.Column('wechat_unionid', sa.String(length=255), nullable=True),
    sa.Column('registration_source', sa.String(length=50), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_apple_id'), ['apple_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_unionid'), ['wechat_unionid'], unique=True)

    op.create_table('behavior_patterns',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution_text', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavior_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_patterns_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_patterns_user_id'), ['user_id'], unique=False)

    op.create_table('friendships',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('friend_id', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'), nullable=False),
    sa.Column('initiated_by', app.models.base.GUID(), nullable=False),
    sa.Column('match_reason', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index('idx_friendship_friend', ['friend_id'], unique=False)
        batch_op.create_index('idx_friendship_status', ['status'], unique=False)
        batch_op.create_index('idx_friendship_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id'), ['user_id'], unique=False)

    op.create_table('group_members',
    sa.Column('group_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='grouprole'), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('flame_contribution', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('checkin_streak', sa.Integer(), nullable=False),
    sa.Column('last_checkin_date', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('idx_member_group', ['group_id'], unique=False)
        batch_op.create_index('idx_member_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    op.create_table('group_messages',
    sa.Column('group_id', app.models.base.GUID(), nullable=False),
    sa.Column('sender_id', app.models.base.GUID(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'TASK_SHARE', 'PLAN_SHARE', 'FRAGMENT_SHARE', 'PROGRESS', 'ACHIEVEMENT', 'CHECKIN', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('reply_to_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['group_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_group_time', ['group_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_group_id'), ['group_id'], unique=False)

    op.create_table('group_tasks',
    sa.Column('group_id', app.models.base.GUID(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('total_completions', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_group_task_group', ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_tasks_group_id'), ['group_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index('idx_idempotency_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_status', ['status'], unique=False)
        batch_op.create_index('idx_jobs_status_timeout', ['status', 'timeout_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
        batch_op.create_index('idx_jobs_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_nodes',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_task_id', app.models.base.GUID(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_subject_id'), ['subject_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SPRINT', 'GROWTH', name='plantype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('daily_available_minutes', sa.Integer(), nullable=False),
    sa.Column('total_estimated_hours', sa.Float(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index('idx_plans_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_plans_target_date', ['target_date'], unique=False)
        batch_op.create_index('idx_plans_type', ['type'], unique=False)
        batch_op.create_index('idx_plans_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('private_messages',
    sa.Column('sender_id', app.models.base.GUID(), nullable=False),
    sa.Column('receiver_id', app.models.base.GUID(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'TASK_SHARE', 'PLAN_SHARE', 'FRAGMENT_SHARE', 'PROGRESS', 'ACHIEVEMENT', 'CHECKIN', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('reply_to_id', app.models.base.GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['private_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.create_index('idx_private_message_conversation', ['sender_id', 'receiver_id', 'created_at'], unique=False)
        batch_op.create_index('idx_private_message_receiver_unread', ['receiver_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_private_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_private_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_private_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('push_histories',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_histories_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_histories_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_histories_user_id'), ['user_id'], unique=False)

    op.create_table('push_preferences',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('active_slots', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('enable_curiosity', sa.Boolean(), nullable=False),
    sa.Column('persona_type', sa.String(length=50), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('last_push_time', sa.DateTime(), nullable=True),
    sa.Column('consecutive_ignores', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_preferences_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_daily_metrics',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_focus_minutes', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_created', sa.Integer(), nullable=True),
    sa.Column('nodes_studied', sa.Integer(), nullable=True),
    sa.Column('mastery_gained', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('average_mood', sa.Float(), nullable=True),
    sa.Column('anxiety_score', sa.Float(), nullable=True),
    sa.Column('chat_messages_count', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_metric')
    )
    with op.batch_alter_table('user_daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_metrics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_metrics_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('node_relations',
    sa.Column('source_node_id', app.models.base.GUID(), nullable=False),
    sa.Column('target_node_id', app.models.base.GUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_relations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_relations_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_relations_target_node_id'), ['target_node_id'], unique=False)

    op.create_table('tasks',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('plan_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('LEARNING', 'TRAINING', 'ERROR_FIX', 'REFLECTION', 'SOCIAL', 'PLANNING', name='tasktype'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=False),
    sa.Column('guide_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='taskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('knowledge_node_id', app.models.base.GUID(), nullable=True),
    sa.Column('auto_expand_enabled', sa.Boolean(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_tasks_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_tasks_plan_id', ['plan_id'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_tasks_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('user_node_status',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('node_id', app.models.base.GUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('total_study_minutes', sa.Integer(), nullable=False),
    sa.Column('study_count', sa.Integer(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('is_collapsed', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('last_study_at', sa.DateTime(), nullable=True),
    sa.Column('last_interacted_at', sa.DateTime(), nullable=False),
    sa.Column('decay_paused', sa.Boolean(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('first_unlock_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    with op.batch_alter_table('user_node_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_node_status_next_review_at'), ['next_review_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('parse_degraded', sa.Boolean(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_chat_role', ['role'], unique=False)
        batch_op.create_index('idx_chat_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_chat_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_chat_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('cognitive_fragments',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_url', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('error_tags', sa.JSON(), nullable=True),
    sa.Column('context_tags', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cognitive_fragments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cognitive_fragments_user_id'), ['user_id'], unique=False)

    op.create_table('curiosity_capsules',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_subject', sa.String(length=255), nullable=True),
    sa.Column('related_task_id', app.models.base.GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curiosity_capsules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curiosity_capsules_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_curiosity_capsules_related_task_id'), ['related_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curiosity_capsules_user_id'), ['user_id'], unique=False)

    op.create_table('error_records',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('correct_approach', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.create_index('idx_error_is_resolved', ['is_resolved'], unique=False)
        batch_op.create_index('idx_error_last_occurred', ['last_occurred_at'], unique=False)
        batch_op.create_index('idx_error_subject', ['subject'], unique=False)
        batch_op.create_index('idx_error_subject_topic', ['subject', 'topic'], unique=False)
        batch_op.create_index('idx_error_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_error_topic', ['topic'], unique=False)
        batch_op.create_index('idx_error_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_user_id'), ['user_id'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('focus_type', sa.Enum('POMODORO', 'STOPWATCH', name='focustype'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'INTERRUPTED', name='focusstatus'), nullable=False),
    sa.Column('white_noise_type', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_focus_user_time', ['user_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('group_task_claims',
    sa.Column('group_task_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('personal_task_id', app.models.base.GUID(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_task_id'], ['group_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personal_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_task_id', 'user_id', name='uq_task_claim')
    )
    with op.batch_alter_table('group_task_claims', schema=None) as batch_op:
        batch_op.create_index('idx_claim_task', ['group_task_id'], unique=False)
        batch_op.create_index('idx_claim_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_task_claims_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_task_claims_group_task_id'), ['group_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_task_claims_user_id'), ['user_id'], unique=False)

    op.create_table('node_expansion_queue',
    sa.Column('trigger_node_id', app.models.base.GUID(), nullable=False),
    sa.Column('trigger_task_id', app.models.base.GUID(), nullable=True),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('expansion_context', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expanded_nodes', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trigger_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['trigger_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_expansion_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_expansion_queue_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_expansion_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_expansion_queue_user_id'), ['user_id'], unique=False)

    op.create_table('study_records',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('node_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.Column('mastery_delta', sa.Float(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_records_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_records_user_id'), ['user_id'], unique=False)

    op.create_table('word_books',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('source_task_id', app.models.base.GUID(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_user_word')
    )
    with op.batch_alter_table('word_books', schema=None) as batch_op:
        batch_op.create_index('idx_wordbook_review', ['user_id', 'next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_books_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_books_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_books_word'), ['word'], unique=False)

    op.create_table('shared_resources',
    sa.Column('group_id', app.models.base.GUID(), nullable=True),
    sa.Column('target_user_id', app.models.base.GUID(), nullable=True),
    sa.Column('shared_by', app.models.base.GUID(), nullable=False),
    sa.Column('plan_id', app.models.base.GUID(), nullable=True),
    sa.Column('task_id', app.models.base.GUID(), nullable=True),
    sa.Column('cognitive_fragment_id', app.models.base.GUID(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('save_count', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cognitive_fragment_id'], ['cognitive_fragments.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_resources', schema=None) as batch_op:
        batch_op.create_index('idx_share_group', ['group_id'], unique=False)
        batch_op.create_index('idx_share_resource_plan', ['plan_id'], unique=False)
        batch_op.create_index('idx_share_target_user', ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_resources_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_resources_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_resources_target_user_id'), ['target_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_resources_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_shared_resources_group_id'))
        batch_op.drop_index(batch_op.f('ix_shared_resources_deleted_at'))
        batch_op.drop_index('idx_share_target_user')
        batch_op.drop_index('idx_share_resource_plan')
        batch_op.drop_index('idx_share_group')

    op.drop_table('shared_resources')
    with op.batch_alter_table('word_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_books_word'))
        batch_op.drop_index(batch_op.f('ix_word_books_user_id'))
        batch_op.drop_index(batch_op.f('ix_word_books_deleted_at'))
        batch_op.drop_index('idx_wordbook_review')

    op.drop_table('word_books')
    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_records_node_id'))
        batch_op.drop_index(batch_op.f('ix_study_records_deleted_at'))

    op.drop_table('study_records')
    with op.batch_alter_table('node_expansion_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_expansion_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_node_expansion_queue_status'))
        batch_op.drop_index(batch_op.f('ix_node_expansion_queue_deleted_at'))

    op.drop_table('node_expansion_queue')
    with op.batch_alter_table('group_task_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_task_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_task_claims_group_task_id'))
        batch_op.drop_index(batch_op.f('ix_group_task_claims_deleted_at'))
        batch_op.drop_index('idx_claim_user')
        batch_op.drop_index('idx_claim_task')

    op.drop_table('group_task_claims')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_deleted_at'))
        batch_op.drop_index('idx_focus_user_time')

    op.drop_table('focus_sessions')
    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_error_records_topic'))
        batch_op.drop_index(batch_op.f('ix_error_records_subject'))
        batch_op.drop_index(batch_op.f('ix_error_records_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_error_records_deleted_at'))
        batch_op.drop_index('idx_error_user_id')
        batch_op.drop_index('idx_error_topic')
        batch_op.drop_index('idx_error_task_id')
        batch_op.drop_index('idx_error_subject_topic')
        batch_op.drop_index('idx_error_subject')
        batch_op.drop_index('idx_error_last_occurred')
        batch_op.drop_index('idx_error_is_resolved')

    op.drop_table('error_records')
    with op.batch_alter_table('curiosity_capsules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curiosity_capsules_user_id'))
        batch_op.drop_index(batch_op.f('ix_curiosity_capsules_related_task_id'))
        batch_op.drop_index(batch_op.f('ix_curiosity_capsules_deleted_at'))

    op.drop_table('curiosity_capsules')
    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cognitive_fragments_user_id'))
        batch_op.drop_index(batch_op.f('ix_cognitive_fragments_deleted_at'))

    op.drop_table('cognitive_fragments')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_deleted_at'))
        batch_op.drop_index('idx_chat_user_id')
        batch_op.drop_index('idx_chat_task_id')
        batch_op.drop_index('idx_chat_session_id')
        batch_op.drop_index('idx_chat_role')
        batch_op.drop_index('idx_chat_created_at')

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_node_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_node_status_next_review_at'))

    op.drop_table('user_node_status')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.drop_index('idx_tasks_user_id')
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_plan_id')
        batch_op.drop_index('idx_tasks_due_date')
        batch_op.drop_index('idx_tasks_created_at')

    op.drop_table('tasks')
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_relations_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_node_relations_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_node_relations_deleted_at'))

    op.drop_table('node_relations')
    with op.batch_alter_table('user_daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_daily_metrics_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_user_daily_metrics_date'))

    op.drop_table('user_daily_metrics')
    with op.batch_alter_table('push_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_preferences_deleted_at'))

    op.drop_table('push_preferences')
    with op.batch_alter_table('push_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_histories_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_histories_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_push_histories_content_hash'))

    op.drop_table('push_histories')
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_private_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_private_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_private_messages_deleted_at'))
        batch_op.drop_index('idx_private_message_receiver_unread')
        batch_op.drop_index('idx_private_message_conversation')

    op.drop_table('private_messages')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_plans_is_active'))
        batch_op.drop_index(batch_op.f('ix_plans_deleted_at'))
        batch_op.drop_index('idx_plans_user_id')
        batch_op.drop_index('idx_plans_type')
        batch_op.drop_index('idx_plans_target_date')
        batch_op.drop_index('idx_plans_is_active')

    op.drop_table('plans')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_deleted_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_subject_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_deleted_at'))

    op.drop_table('knowledge_nodes')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_deleted_at'))
        batch_op.drop_index('idx_jobs_user_id')
        batch_op.drop_index('idx_jobs_status_timeout', postgresql_where=sa.text("status = 'running'"))
        batch_op.drop_index('idx_jobs_status')

    op.drop_table('jobs')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_expires_at'))
        batch_op.drop_index('idx_idempotency_expires')

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('group_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_tasks_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_tasks_deleted_at'))
        batch_op.drop_index('idx_group_task_group')

    op.drop_table('group_tasks')
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_deleted_at'))
        batch_op.drop_index('idx_message_group_time')

    op.drop_table('group_messages')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_deleted_at'))
        batch_op.drop_index('idx_member_user')
        batch_op.drop_index('idx_member_group')

    op.drop_table('group_members')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_friend_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_deleted_at'))
        batch_op.drop_index('idx_friendship_user')
        batch_op.drop_index('idx_friendship_status')
        batch_op.drop_index('idx_friendship_friend')

    op.drop_table('friendships')
    with op.batch_alter_table('behavior_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_patterns_user_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_patterns_deleted_at'))

    op.drop_table('behavior_patterns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wechat_unionid'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_apple_id'))
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_name'))
        batch_op.drop_index(batch_op.f('ix_subjects_is_active'))
        batch_op.drop_index(batch_op.f('ix_subjects_category'))

    op.drop_table('subjects')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_deleted_at'))
        batch_op.drop_index('idx_group_type')
        batch_op.drop_index('idx_group_public')

    op.drop_table('groups')
    with op.batch_alter_table('dictionary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_entries_word'))
        batch_op.drop_index(batch_op.f('ix_dictionary_entries_deleted_at'))
        batch_op.drop_index('idx_dict_word')

    op.drop_table('dictionary_entries')

    # Drop pgvector extension (only if we're rolling back everything)
    # Note: This is safe because IF EXISTS prevents errors if it's not present
    op.execute("DROP EXTENSION IF EXISTS vector CASCADE")
    # ### end Alembic commands ###
