"""add_focus_sessions

Revision ID: 3682fd8c7978
Revises: 8017baa9410f
Create Date: 2025-12-23 23:14:33.153432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision: str = '3682fd8c7978'
down_revision: Union[str, None] = '8017baa9410f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
        sa.Column('user_id', GUID(), nullable=False),
        sa.Column('task_id', GUID(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('focus_type', sa.Enum('POMODORO', 'STOPWATCH', name='focustype'), nullable=False),
        sa.Column('status', sa.Enum('COMPLETED', 'INTERRUPTED', name='focusstatus'), nullable=False),
        sa.Column('white_noise_type', sa.Integer(), nullable=True),
        sa.Column('id', GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_focus_user_time', ['user_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)

    op.drop_table('focus_sessions')
    # ### end Alembic commands ###
