"""Initial schema with all models

Revision ID: 5504e72df4f0
Revises: 
Create Date: 2025-12-14 21:35:20.772433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision: str = '5504e72df4f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('flame_level', sa.Integer(), nullable=False),
    sa.Column('flame_brightness', sa.Float(), nullable=False),
    sa.Column('depth_preference', sa.Float(), nullable=False),
    sa.Column('curiosity_preference', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('plans',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SPRINT', 'GROWTH', name='plantype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('daily_available_minutes', sa.Integer(), nullable=False),
    sa.Column('total_estimated_hours', sa.Float(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plans_is_active', 'plans', ['is_active'], unique=False)
    op.create_index('idx_plans_target_date', 'plans', ['target_date'], unique=False)
    op.create_index('idx_plans_type', 'plans', ['type'], unique=False)
    op.create_index('idx_plans_user_id', 'plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('plan_id', GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('LEARNING', 'TRAINING', 'ERROR_FIX', 'REFLECTION', 'SOCIAL', 'PLANNING', name='tasktype'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=False),
    sa.Column('guide_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='taskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_plan_id', 'tasks', ['plan_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_plan_id'), 'tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=True),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_chat_role', 'chat_messages', ['role'], unique=False)
    op.create_index('idx_chat_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_chat_task_id', 'chat_messages', ['task_id'], unique=False)
    op.create_index('idx_chat_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('error_records',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('correct_approach', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_is_resolved', 'error_records', ['is_resolved'], unique=False)
    op.create_index('idx_error_last_occurred', 'error_records', ['last_occurred_at'], unique=False)
    op.create_index('idx_error_subject', 'error_records', ['subject'], unique=False)
    op.create_index('idx_error_subject_topic', 'error_records', ['subject', 'topic'], unique=False)
    op.create_index('idx_error_task_id', 'error_records', ['task_id'], unique=False)
    op.create_index('idx_error_topic', 'error_records', ['topic'], unique=False)
    op.create_index('idx_error_user_id', 'error_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_error_records_is_resolved'), 'error_records', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_error_records_subject'), 'error_records', ['subject'], unique=False)
    op.create_index(op.f('ix_error_records_topic'), 'error_records', ['topic'], unique=False)
    op.create_index(op.f('ix_error_records_user_id'), 'error_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_records_user_id'), table_name='error_records')
    op.drop_index(op.f('ix_error_records_topic'), table_name='error_records')
    op.drop_index(op.f('ix_error_records_subject'), table_name='error_records')
    op.drop_index(op.f('ix_error_records_is_resolved'), table_name='error_records')
    op.drop_index('idx_error_user_id', table_name='error_records')
    op.drop_index('idx_error_topic', table_name='error_records')
    op.drop_index('idx_error_task_id', table_name='error_records')
    op.drop_index('idx_error_subject_topic', table_name='error_records')
    op.drop_index('idx_error_subject', table_name='error_records')
    op.drop_index('idx_error_last_occurred', table_name='error_records')
    op.drop_index('idx_error_is_resolved', table_name='error_records')
    op.drop_table('error_records')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('idx_chat_user_id', table_name='chat_messages')
    op.drop_index('idx_chat_task_id', table_name='chat_messages')
    op.drop_index('idx_chat_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_role', table_name='chat_messages')
    op.drop_index('idx_chat_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_plan_id'), table_name='tasks')
    op.drop_index('idx_tasks_user_id', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_plan_id', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_index('idx_plans_user_id', table_name='plans')
    op.drop_index('idx_plans_type', table_name='plans')
    op.drop_index('idx_plans_target_date', table_name='plans')
    op.drop_index('idx_plans_is_active', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
