"""enhance_cognitive_prism_v2

Revision ID: 5b2de404d0e4
Revises: 87ffdcc9b5d4
Create Date: 2025-12-23 21:26:46.049016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision: str = '5b2de404d0e4'
down_revision: Union[str, None] = '87ffdcc9b5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curiosity_capsules',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_subject', sa.String(length=255), nullable=True),
    sa.Column('related_task_id', GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curiosity_capsules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curiosity_capsules_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_curiosity_capsules_related_task_id'), ['related_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curiosity_capsules_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('behavior_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.Integer(), nullable=True))

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=20), server_default='text', nullable=False))
        batch_op.add_column(sa.Column('resource_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('error_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('context_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.Integer(), server_default='1', nullable=False))
        # Remove vector type change for SQLite compatibility
        # batch_op.alter_column('embedding', ...

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.drop_column('severity')
        batch_op.drop_column('context_tags')
        batch_op.drop_column('error_tags')
        batch_op.drop_column('resource_url')
        batch_op.drop_column('resource_type')

    with op.batch_alter_table('behavior_patterns', schema=None) as batch_op:
        batch_op.drop_column('frequency')
        batch_op.drop_column('confidence_score')

    with op.batch_alter_table('curiosity_capsules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curiosity_capsules_user_id'))
        batch_op.drop_index(batch_op.f('ix_curiosity_capsules_related_task_id'))
        batch_op.drop_index(batch_op.f('ix_curiosity_capsules_deleted_at'))

    op.drop_table('curiosity_capsules')
    # ### end Alembic commands ###
