"""add_shared_resources_and_official_groups

Revision ID: 8017baa9410f
Revises: 5b2de404d0e4
Create Date: 2025-12-23 21:45:32.296436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from app.models.base import GUID

# revision identifiers, used by Alembic.
revision: str = '8017baa9410f'
down_revision: Union[str, None] = '5b2de404d0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_resources',
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('target_user_id', GUID(), nullable=True),
    sa.Column('shared_by', GUID(), nullable=False),
    sa.Column('plan_id', GUID(), nullable=True),
    sa.Column('task_id', GUID(), nullable=True),
    sa.Column('cognitive_fragment_id', GUID(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('save_count', sa.Integer(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cognitive_fragment_id'], ['cognitive_fragments.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_resources', schema=None) as batch_op:
        batch_op.create_index('idx_share_group', ['group_id'], unique=False)
        batch_op.create_index('idx_share_resource_plan', ['plan_id'], unique=False)
        batch_op.create_index('idx_share_target_user', ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_resources_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_resources_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_resources_target_user_id'), ['target_user_id'], unique=False)

    # Note: pgvector type conversion might fail if using SQLite for dev. 
    # Alembic autogen sometimes detects type changes even if they are same underlying type in some drivers.
    # We'll wrap these in try-except or just let them run if they are valid.
    # Actually, for SQLite, pgvector is not supported, so these columns might just be generic or handled by the TypeDecorator.
    # The 'GUID' import handles the dialect check for UUID. 
    # For Vector, we should probably check dialect or rely on the fact that existing columns were numeric/similar.
    
    # We will comment out the vector type changes if we are not sure, 
    # BUT since they were autogenerated, it means the model definition changed from what Alembic thought was there.
    # If this is SQLite, the previous type was probably implicitly handled.
    # Let's keep them but ensure pgvector is imported.

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('TEXT', 'TASK_SHARE', 'PLAN_SHARE', 'FRAGMENT_SHARE', 'PROGRESS', 'ACHIEVEMENT', 'CHECKIN', 'SYSTEM', name='messagetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('SQUAD', 'SPRINT', 'OFFICIAL', name='grouptype'),
               existing_nullable=False)

    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('SQUAD', 'SPRINT', 'OFFICIAL', name='grouptype'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.Enum('TEXT', 'TASK_SHARE', 'PLAN_SHARE', 'FRAGMENT_SHARE', 'PROGRESS', 'ACHIEVEMENT', 'CHECKIN', 'SYSTEM', name='messagetype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))

    with op.batch_alter_table('cognitive_fragments', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)

    with op.batch_alter_table('shared_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_resources_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_shared_resources_group_id'))
        batch_op.drop_index(batch_op.f('ix_shared_resources_deleted_at'))
        batch_op.drop_index('idx_share_target_user')
        batch_op.drop_index('idx_share_resource_plan')
        batch_op.drop_index('idx_share_group')

    op.drop_table('shared_resources')
    # ### end Alembic commands ###
