"""add_user_daily_metrics

Revision ID: 87ffdcc9b5d4
Revises: ad7a53964495
Create Date: 2025-12-23 21:06:52.344729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ffdcc9b5d4'
down_revision: Union[str, None] = 'ad7a53964495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_metrics',
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_focus_minutes', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_created', sa.Integer(), nullable=True),
    sa.Column('nodes_studied', sa.Integer(), nullable=True),
    sa.Column('mastery_gained', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('average_mood', sa.Float(), nullable=True),
    sa.Column('anxiety_score', sa.Float(), nullable=True),
    sa.Column('chat_messages_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_metric')
    )
    with op.batch_alter_table('user_daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_metrics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_metrics_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_metrics_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_daily_metrics_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_user_daily_metrics_date'))

    op.drop_table('user_daily_metrics')
    # ### end Alembic commands ###