"""add_galaxy_models

Revision ID: b3849bc7b0cd
Revises: 6a9c3cc94147
Create Date: 2025-12-16 16:29:43.347436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'b3849bc7b0cd'
down_revision: Union[str, None] = '6a9c3cc94147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_subject_id'), ['subject_id'], unique=False)

    op.create_table('user_node_status',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('node_id', app.models.base.GUID(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('last_interacted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_chat_messages_message_id', ['message_id'])

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_error_deleted_at'))
        batch_op.create_index(batch_op.f('ix_error_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_error_records_subject_id', 'subjects', ['subject_id'], ['id'])

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        # batch_op.create_index(batch_op.f('idx_idempotency_expires'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_jobs_deleted_at'))
        batch_op.create_index(batch_op.f('ix_jobs_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.models.base.GUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_plans_deleted_at'))
        batch_op.create_index(batch_op.f('ix_plans_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector_code', sa.String(length=20), server_default='VOID', nullable=False))
        batch_op.add_column(sa.Column('hex_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_subjects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_name'), ['name'], unique=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tasks_deleted_at'))
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_deleted_at'))
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.create_index(batch_op.f('idx_users_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.create_index(batch_op.f('idx_tasks_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_name'))
        batch_op.drop_index(batch_op.f('ix_subjects_is_active'))
        batch_op.drop_index(batch_op.f('ix_subjects_category'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('hex_color')
        batch_op.drop_column('sector_code')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_deleted_at'))
        batch_op.create_index(batch_op.f('idx_plans_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_deleted_at'))
        batch_op.create_index(batch_op.f('idx_jobs_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_expires_at'))
        batch_op.drop_index('idx_idempotency_expires')

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_error_records_subject_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_error_records_deleted_at'))
        batch_op.create_index(batch_op.f('idx_error_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chat_messages_message_id', type_='unique')

    op.drop_table('user_node_status')
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_subject_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_deleted_at'))

    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
