// Mocks generated by Mockito 5.4.4 from annotations
// in sparkle/test/unit/galaxy_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sparkle/core/network/api_client.dart' as _i6;
import 'package:sparkle/data/models/galaxy_model.dart' as _i2;
import 'package:sparkle/data/models/knowledge_detail_model.dart' as _i3;
import 'package:sparkle/data/repositories/galaxy_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGalaxyGraphResponse_0 extends _i1.SmartFake
    implements _i2.GalaxyGraphResponse {
  _FakeGalaxyGraphResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKnowledgeDetailResponse_1 extends _i1.SmartFake
    implements _i3.KnowledgeDetailResponse {
  _FakeKnowledgeDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GalaxyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalaxyRepository extends _i1.Mock implements _i4.GalaxyRepository {
  MockGalaxyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GalaxyGraphResponse> getGraph({double? zoomLevel = 1.0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGraph,
          [],
          {#zoomLevel: zoomLevel},
        ),
        returnValue: _i5.Future<_i2.GalaxyGraphResponse>.value(
            _FakeGalaxyGraphResponse_0(
          this,
          Invocation.method(
            #getGraph,
            [],
            {#zoomLevel: zoomLevel},
          ),
        )),
      ) as _i5.Future<_i2.GalaxyGraphResponse>);

  @override
  _i5.Future<void> sparkNode(String? id) => (super.noSuchMethod(
        Invocation.method(
          #sparkNode,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i6.SSEEvent> getGalaxyEventsStream() => (super.noSuchMethod(
        Invocation.method(
          #getGalaxyEventsStream,
          [],
        ),
        returnValue: _i5.Stream<_i6.SSEEvent>.empty(),
      ) as _i5.Stream<_i6.SSEEvent>);

  @override
  _i5.Future<_i3.KnowledgeDetailResponse> getNodeDetail(String? nodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNodeDetail,
          [nodeId],
        ),
        returnValue: _i5.Future<_i3.KnowledgeDetailResponse>.value(
            _FakeKnowledgeDetailResponse_1(
          this,
          Invocation.method(
            #getNodeDetail,
            [nodeId],
          ),
        )),
      ) as _i5.Future<_i3.KnowledgeDetailResponse>);

  @override
  _i5.Future<_i3.KnowledgeDetailResponse?> predictNextNode() =>
      (super.noSuchMethod(
        Invocation.method(
          #predictNextNode,
          [],
        ),
        returnValue: _i5.Future<_i3.KnowledgeDetailResponse?>.value(),
      ) as _i5.Future<_i3.KnowledgeDetailResponse?>);

  @override
  _i5.Future<List<_i2.GalaxySearchResult>> searchNodes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNodes,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.GalaxySearchResult>>.value(
            <_i2.GalaxySearchResult>[]),
      ) as _i5.Future<List<_i2.GalaxySearchResult>>);

  @override
  _i5.Future<void> toggleFavorite(String? nodeId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [nodeId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pauseDecay(
    String? nodeId,
    bool? pause,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pauseDecay,
          [
            nodeId,
            pause,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
